tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "primary":                      "#012d1d",
                "on-primary":                   "#ffffff",
                "primary-container":            "#1b4332",
                "on-primary-container":         "#86af99",
                "primary-fixed":                "#c1ecd4",
                "primary-fixed-dim":            "#a5d0b9",
                "on-primary-fixed":             "#002114",
                "on-primary-fixed-variant":     "#274e3d",
                "inverse-primary":              "#a5d0b9",

                "secondary":                    "#50652a",
                "on-secondary":                 "#ffffff",
                "secondary-container":          "#cfe99f",
                "on-secondary-container":       "#546a2e",
                "secondary-fixed":              "#d2eca2",
                "secondary-fixed-dim":          "#b6d088",
                "on-secondary-fixed":           "#131f00",
                "on-secondary-fixed-variant":   "#394d14",

                "tertiary":                     "#55000b",
                "on-tertiary":                  "#ffffff",
                "tertiary-container":           "#77131c",
                "on-tertiary-container":        "#ff807f",
                "tertiary-fixed":               "#ffdad8",
                "tertiary-fixed-dim":           "#ffb3b0",
                "on-tertiary-fixed":            "#410007",
                "on-tertiary-fixed-variant":    "#861f25",

                "error":                        "#ba1a1a",
                "on-error":                     "#ffffff",
                "error-container":              "#ffdad6",
                "on-error-container":           "#93000a",

                "background":                   "#f8faf8",
                "on-background":                "#191c1b",
                "surface":                      "#f8faf8",
                "surface-dim":                  "#d8dad9",
                "surface-bright":               "#f8faf8",
                "surface-container-lowest":     "#ffffff",
                "surface-container-low":        "#f2f4f2",
                "surface-container":            "#eceeec",
                "surface-container-high":       "#e6e9e7",
                "surface-container-highest":    "#e1e3e1",
                "surface-variant":              "#e1e3e1",
                "surface-tint":                 "#3f6653",
                "on-surface":                   "#191c1b",
                "on-surface-variant":           "#414844",
                "inverse-surface":              "#2e3130",
                "inverse-on-surface":           "#eff1ef",

                "outline":                      "#717973",
                "outline-variant":              "#c1c8c2",
            },
            borderRadius: {
                DEFAULT: "0.5rem",
                lg:      "1rem",
                xl:      "1.5rem",
                full:    "9999px",
            },
            fontFamily: {
                headline: ["Manrope"],
                body:     ["Inter"],
                label:    ["Inter"],
            },
        },
    },
};
